### ISSUE TITLE
The requirement.txt

### ISSUE THREAD

**Issue by Gio-CCHAN** [cchen23/ctp#1]
hi chen,

I could not follow your step of the installation to finish the environment setting as there is no requirements.txt in the GitHub repo.
Can you kindly provide the requirements.txt for the package needed? or just list the related package and the version #.

**Comment by cchen23** [comment]
Hi @Giochen, we have just uploaded a requirements.txt. Could you please re-try installation?

**Comment by Gio-CCHAN** [comment]
Thx! it is fine as I just want to see if there is some specific version of the package needed.
