### ISSUE TITLE
Matching configuration names

### ISSUE THREAD

**Issue by jeslev** [cchen23/ctp#2]
Hello, thanks for your work.
I want to reproduce results from Table 2, however, I am not able to identify the corresponding configuration file to do it.
Also, I have the same problem to filter the datasets with and without the glosses.
Can you facilitate this information, please?

Thanks!

**Comment by cchen23** [comment]
Hi @jeslev, the results in Table 2 are averaged over three random seeds, using the learning rates and random seeds described in Tables 13 and 14 of the Appendix. The config files for one of the random seeds can be found in [WN_par_roberta_large_1e6_seed2.json](https://github.com/cchen23/ctp/blob/21a39b978b2c3a484627e608a17e02db1d7419a6/ctp/experiment_configs/WN_par_roberta_large_1e6_seed2.json) for the non-retrieval model, [WN_par_retrieval_roberta_large_1e6_seed2.json](https://github.com/cchen23/ctp/blob/master/ctp/experiment_configs/WN_par_retrieval_roberta_large_1e6_seed2.json) for the model with retrieved web glosses, and [WN_par_roberta_large_1e6_wordnet_defs_seed2.json](https://github.com/cchen23/ctp/blob/master/ctp/experiment_configs/WN_par_roberta_large_1e6_wordnet_defs_seed2.json) for the model with retrieved oracle glosses.

Could you describe what problem you are having with filtering datasets with and without glosses?

**Comment by jeslev** [comment]
Thanks for your answer. Your config files description solves the problem I was having :)
